# Generated by Django 5.0 on 2023-12-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teacher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=75)),
                ('number', models.CharField(max_length=13)),
                ('check_photo', models.ImageField(blank=True, null=True, upload_to='check_photos/')),
            ],
        ),
    ]
