# Generated by Django 5.0 on 2023-12-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_courses_delete_videotutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='age',
            field=models.CharField(max_length=30),
        ),
    ]
